@import gg.jte.Content
@param Content header
@param Content footer

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Hexlet Javalin Example</title>
    </head>
    <body>
        <header>
            ${header}
        </header>

        <div class="footer">
            ${footer}
        </div>

    </body>
</html>
